spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/blog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    # username: user
    # password: password

    url: jdbc:mysql://thdwjdrl.com/blog?zeroDateTimeBehavior=convertToNull&autoReconnect=true&useUnicode=true&allowMultiQueries=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: thdwjdrlelql

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    # show-sql: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    org:
      springframework:
        # security: DEBUG
      hibernate:
        # SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
